---
title: "Main code"
author: "Margaret Perry"
date: "November 16, 2018"
output: pdf_document
---

```{r, echo=FALSE}
library(haven)
library(tidyr)
library(dplyr)
library(mosaic)
```

##Names (eating disorder)
```{r}
library(readr)
library(haven)
#raw_data <- read_sav("enter your own file path")
eatdisord_1 <- read_csv("Variblenamefiles/eatdisord_1.csv")
sub_use_1 <- read_csv("Variblenamefiles/sub_use_1.csv")
socnet<- read_csv("Variblenamefiles/socialnetworks.csv")
tobacco_1<- read_csv("Variblenamefiles/Tobacco_1.csv")
alcohol<- read_csv("Variblenamefiles/alcohol.csv")
social_ph<- read_csv("Variblenamefiles/Soicalph.csv")
persona<- read_csv("Variblenamefiles/personality_1.csv")
marriage<- read_csv("Variblenamefiles/marriage.csv")
ner_at<- read_csv("Variblenamefiles/nervous_attack.csv")
discrim<- read_csv("Variblenamefiles/discrimination.csv")
demograph<- read_csv("Variblenamefiles/demographics.csv")
family<- read_csv("Variblenamefiles/family.csv")
family_n_friends<- read_csv("Variblenamefiles/family_n_friends.csv")
depress<- read_csv("Variblenamefiles/drepression.csv")
suicide<- read_csv("Variblenamefiles/Suicide.csv")


"Uncomment when uploading raw data however the raw dataset is too large for Git"
```

```{r}
#Read in Var names

#Main
eatdisord_1<- select(eatdisord_1, CPES, Eating_Disorder)
eatdisord_1= drop_na(eatdisord_1)
View(eatdisord_1)

#CPES
CPES_ed= select(eatdisord_1, CPES)
View(CPES_ed)

#Full_explaination
full_name= select(eatdisord_1, Eating_Disorder)
View(full_name)

#Make it a list
namelist = as.list(full_name)
'print(namelist)'
' We did not need this and can join on just the CPES code and maintain the information of the varible'
```

##Making Subset(eating disorder)

```{r}
data_ed= select(raw_data, CPES_ed$CPES[1:64])
View(test_ed)
```

#Substance varibles 
```{r}
#Main
sub_use_1<- select(sub_use_1, CPES)
sub_use_1= drop_na(sub_use_1)
#View(sub_use_1)

#Make it a list
namelist_su = as.list(sub_use_1)
data_su= select(raw_data, sub_use_1$CPES[1:70])
```

#Tobacco
```{r}
#Main
tobacco_1<- select(tobacco_1, CPES)
tobacco_1= drop_na(tobacco_1)
#Make it a list
namelist_to = as.list(tobacco_1)
data_to= select(raw_data, tobacco_1$CPES[1:65])
```

#Social Phobia
```{r}
#Main
social_ph<- select(social_ph, CPES)
social_ph= drop_na(social_ph)
#Make it a list
namelist_sph = as.list(social_ph)
data_sph= select(raw_data, social_ph$CPES[1:87])
```

#Personality
```{r}
#Main
persona<- select(persona, CPES)
persona= drop_na(persona)
#Make it a list
namelist_per = as.list(persona)
data_per= select(raw_data, namelist_per$CPES[1:44])
```

#Marriage
```{r}
#Main
marriage<- select(marriage, CPES)
marriage= drop_na(marriage)
#Make it a list
namelist_mar = as.list(marriage)
data_mar= select(raw_data, namelist_mar$CPES[1:29])
```

#Social Networks

```{r}
#Main
socnet<- select(socnet, CPES)
socnet= drop_na(socnet)
#Make it a list
namelist_sn = as.list(socnet)
data_sn= select(raw_data, namelist_sn$CPES[1:15])
```

#Nervous Attack
```{r}
#Main
ner_at<- select(ner_at, CPES)
ner_at= drop_na(ner_at)
#Make it a list
namelist_nerv = as.list(ner_at)
data_nerv= select(raw_data, namelist_nerv$CPES[1:23])
```

#Discrimination

```{r}
#Main
discrim<- select(discrim, CPES)
discrim= drop_na(discrim)
#Make it a list
namelist_disc = as.list(discrim)
data_disc= select(raw_data, namelist_disc$CPES[1:13])
```

#Demographics
```{r}
#Main
demograph<- select(demograph, CPES)
demograph= drop_na(demograph)
#Make it a list
namelist_dem= as.list(demograph)
data_dem= select(raw_data, namelist_dem$CPES[1:14])
```

#Family Cohesion

```{r}
#Main
family<- select(family, CPES)
family= drop_na(family)
#Make it a list
namelist_fam = as.list(family)
data_fam= select(raw_data, namelist_fam$CPES[1:15])
```
#Family and Friends
```{r}
#Main
family_n_friends<- select(family_n_friends, CPES)
family_n_friends= drop_na(family_n_friends)
#Make it a list
namelist_ff = as.list(family_n_friends)
data_ff= select(raw_data, namelist_ff$CPES[1:39])
```
#Depression Espoide
```{r}
#Main
depress<- select(depress, CPES)
depress= drop_na(depress)
#Make it a list
namelist_dep = as.list(depress)
data_dep= select(raw_data, namelist_dep$CPES[1:5])
```

#Alcohol
```{r}
#Main
alcohol<- select(alcohol, CPES)
alcohol= drop_na(alcohol)
#Make it a list
namelist_alco = as.list(alcohol)
data_alco= select(raw_data, namelist_alco$CPES[1:5])
```


#Suicide
```{r}
#Main
suicide<- select(suicide, CPES)
suicide= drop_na(suicide)
#Make it a list
namelist_sui = as.list(suicide)
data_sui= select(raw_data, namelist_sui$CPES[1:12])
```
